### ISSUE TITLE
This dependency was not found: @/mixins/overflow

### ISSUE THREAD

**Issue by sefacndmr01** [Bot-Academia/Vue-ui-preloader#51]
Vue3

![image](https://user-images.githubusercontent.com/18026221/118663979-c84a8a00-b7f9-11eb-9005-f61eec214f89.png)

**Comment by vinayaksh42** [comment]
I am looking into it. @sefacndmr01

**Comment by dannycrief** [comment]
I have the same problem. Let me know if you resolve this issue.

**Comment by antonioyosica** [comment]
I got the same problem right now.
@sefacndmr01 did you already fix it?

**Comment by vinayaksh42** [comment]
is this problem occurring in vue 3? @antonioyosica , @dannycrief  and @sefacndmr01

**Comment by salibaray** [comment]
I have the same issue

**Comment by vinayaksh42** [comment]
I hope the issue is now resolved for everyone with the new update of vue-ui-preloader v1.2.0

**Comment by vinayaksh42** [comment]
> I have the same problem. Let me know if you resolve this issue.

It's fixed now @dannycrief , @salibaray , @antonioyosica and @sefacndmr01

**Comment by sefacndmr01** [comment]
@vinayaksh42 Thanks, it works fine now.

**Comment by dannycrief** [comment]
Thank you so much @vinayaksh42 . It works fine
