### ISSUE TITLE
veu 3 support?

### ISSUE THREAD

**Issue by hamedg68** [Bot-Academia/Vue-ui-preloader#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hamedg68** [comment]
does it support vue version 3???

**Comment by sameignatovich** [comment]
@hamedg68 i'm successful using this plugin in Vue 3 project

**Comment by vinayaksh42** [comment]
@sameignatovich can you help us document the right way to use this loader in Vue 3 ?

**Comment by sefacndmr01** [comment]
@vinayaksh42 

Its simple.

Import loader in your main.js like that and use it;

`import loader from "vue-ui-preloader";`
`app.use(loader);`

Example Usage

`<loader v-show="loading" object="#0086f0" color1="#ffffff" color2="#17fd3d" size="5" speed="2" bg="#161c21" objectbg="#999793" opacity="100" disableScrolling="false" name="dots"></loader>`

**Comment by vinayaksh42** [comment]
> @vinayaksh42
> 
> Its simple.
> 
> Import loader in your main.js like that and use it;
> 
> `import loader from "vue-ui-preloader";`
> `app.use(loader);`
> 
> Example Usage
> 
> `<loader v-show="loading" object="#0086f0" color1="#ffffff" color2="#17fd3d" size="5" speed="2" bg="#161c21" objectbg="#999793" opacity="100" disableScrolling="false" name="dots"></loader>`

@sefacndmr01 Thanks

**Comment by gbast0s** [comment]
The loader was not correctly using disable scroll and the compatibility was broken for vue 3.3.6.
I made a new and refresh version with more features, you can suggest more things for the package.
https://github.com/gbast0s/vue3-ui-preloader

**Comment by vinayaksh42** [comment]
> The loader was not correctly using disable scroll and the compatibility was broken for vue 3.3.6. I made a new and refresh version with more features, you can suggest more things for the package. https://github.com/gbast0s/vue3-ui-preloader

How about we merge the two packages into this one so that more people have access to it. vue-ui-preloader has 5.5k users per month. let me know what are your thoughts about it.

**Comment by gbast0s** [comment]
> > The loader was not correctly using disable scroll and the compatibility was broken for vue 3.3.6. I made a new and refresh version with more features, you can suggest more things for the package. https://github.com/gbast0s/vue3-ui-preloader
> 
> How about we merge the two packages into this one so that more people have access to it. vue-ui-preloader has 5.5k users per month. let me know what are your thoughts about it.

That sounds good, but then the package upgrades will be only for vue 3? Will you discard the vue 2 support?

One thing you could do, and I could add you to my current project its to make a reference on top of your README for my current version for Vue 3 users and we "slipt the waters". 
I think its a better way, because of the differences between vue 2 and vue 3 and because of the upgrades that I have in mind for this package.

I think the package was really good, just need some upgrades and maintenance.
