### ISSUE TITLE
Broken dependency of bootstrap / loader not working

### ISSUE THREAD

**Issue by sameignatovich** [Bot-Academia/Vue-ui-preloader#61]
During install process i have several warnings about dependencies:

```
nikita@mbp-Nikita ~/apps/node/project % yarn add vue-ui-preloader
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
warning vue-ui-preloader > bootstrap-vue > popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
...
warning "vue-ui-preloader > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning "vue-ui-preloader > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
...
```

And loader not working at all right now.

**Comment by vinayaksh42** [comment]
I'll fix this in a PR , we don't even require bootstrap for this package but was added by mistake.

**Comment by vinayaksh42** [comment]
@sameignatovich the loader seems to be working correctly now. Kindly update to version 1.2.1
Sandbox link for checking out the latest release - https://codesandbox.io/s/hungry-grass-7fx4z?file=/src/App.vue

**Comment by vinayaksh42** [comment]
@sameignatovich Open a new issue or reopen the current issue in case the problem still exists.
