### ISSUE TITLE
Class overflowHidden stays active after loader disappear

### ISSUE THREAD

**Issue by gbast0s** [Bot-Academia/Vue-ui-preloader#75]
In every type of loader, the body element gets a `"overflowHidden"` class that isn't removed after loader disappears.
You can set `disableScrolling="false"` or `disableScrolling="true"` that doens't do anything.

After that the entire page, lost the ability to scroll through it

**Comment by vinayaksh42** [comment]
@gbast0s Thanks for reporting this issue, I will look into asap
